In [0]:
#Task-1:importing pandas libraries
import pandas as pd

In [0]:
#Task-2:import warnings
import warnings
warnings.filterwarnings("ignore")

In [0]:
#Task-3:Setting Notebook
pd.set_option('display.max_rows',500)
pd.set_option('display.max_columns',500)
pd.set_option('display.width',1000)
pd.set_option('display.expand_frame_repr',False)

In [0]:
#Task-4:importing dataset
ap_data=pd.read_csv('/dbfs/mnt/Datalakedbfs/application_data.csv')
ap_prev=pd.read_csv('/dbfs/mnt/Datalakedbfs/previous_application.csv')

In [0]:
#Task-5:Understanding the dataset
print('Number of rows & columns in application dataset ',ap_data.shape)
print('Number of rows & columns in previous application dataset ',ap_prev.shape)


Number of rows & columns in application dataset (307511, 122)
Number of rows & columns in previous application dataset (1048575, 37)

In [0]:
#Task-6:Checking information of all columns of application dataset
ap_data.info("all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 122 columns):
 # Column Dtype 
--- ------ ----- 
 0 ad_sk_id_curr_ct int64 
 1 ad_target_ct int64 
 2 ad_name_contract_type_ct object 
 3 ad_code_gender_ct object 
 4 ad_flag_own_car_ct object 
 5 ad_flag_own_realty_ct object 
 6 ad_cnt_children_ct int64 
 7 ad_amt_income_total_ct float64
 8 ad_amt_credit_ct float64
 9 ad_amt_annuity_ct float64
 10 ad_amt_goods_price_ct float64
 11 ad_name_type_suite_ct object 
 12 ad_name_income_type_ct object 
 13 ad_name_education_type_ct object 
 14 ad_name_family_status_ct object 
 15 ad_name_housing_type_ct object 
 16 ad_region_population_relative_ct float64
 17 ad_days_birth_ct int64 
 18 ad_days_employed_ct int64 
 19 ad_days_registration_ct float64
 20 ad_days_id_publish_ct int64 
 21 ad_own_car_age_ct float64
 22 ad_flag_mobil_ct int64 
 23 ad_flag_emp_phone_ct int64 
 24 ad_flag_work_phone_ct int64 
 25 ad_flag_cont_mobile_ct int64 
 26 ad_flag_phone_ct int64 
 27 ad_flag_email_ct int64 
 28 ad_occupation_type_ct object 
 29 ad_cnt_fam_members_ct float64
 30 ad_region_rating_client_ct int64 
 31 ad_region_rating_client_w_city_ct int64 
 32 ad_weekday_appr_process_start_ct object 
 33 ad_hour_appr_process_start_ct int64 
 34 ad_reg_region_not_live_region_ct int64 
 35 ad_reg_region_not_work_region_ct int64 
 36 ad_live_region_not_work_region_ct int64 
 37 ad_reg_city_not_live_city_ct int64 
 38 ad_reg_city_not_work_city_ct int64 
 39 ad_live_city_not_work_city_ct int64 
 40 ad_organization_type_ct object 
 41 ad_ext_source_1_ct float64
 42 ad_ext_source_2_ct float64
 43 ad_ext_source_3_ct float64
 44 ad_apartments_avg_ct float64
 45 ad_basementarea_avg_ct float64
 46 ad_years_beginexpluatation_avg_ct float64
 47 ad_years_build_avg_ct float64
 48 ad_commonarea_avg_ct float64
 49 ad_elevators_avg_ct float64
 50 ad_entrances_avg_ct float64
 51 ad_floorsmax_avg_ct float64
 52 ad_floorsmin_avg_ct float64
 53 ad_landarea_avg_ct float64
 54 ad_livingapartments_avg_ct float64
 55 ad_livingarea_avg_ct float64
 56 ad_nonlivingapartments_avg_ct float64
 57 ad_nonlivingarea_avg_ct float64
 58 ad_apartments_mode_ct float64
 59 ad_basementarea_mode_ct float64
 60 ad_years_beginexpluatation_mode_ct float64
 61 ad_years_build_mode_ct float64
 62 ad_commonarea_mode_ct float64
 63 ad_elevators_mode_ct float64
 64 ad_entrances_mode_ct float64
 65 ad_floorsmax_mode_ct float64
 66 ad_floorsmin_mode_ct float64
 67 ad_landarea_mode_ct float64
 68 ad_livingapartments_mode_ct float64
 69 ad_livingarea_mode_ct float64
 70 ad_nonlivingapartments_mode_ct float64
 71 ad_nonlivingarea_mode_ct float64
 72 ad_apartments_medi_ct float64
 73 ad_basementarea_medi_ct float64
 74 ad_years_beginexpluatation_medi_ct float64
 75 ad_years_build_medi_ct float64
 76 ad_commonarea_medi_ct float64
 77 ad_elevators_medi_ct float64
 78 ad_entrances_medi_ct float64
 79 ad_floorsmax_medi_ct float64
 80 ad_floorsmin_medi_ct float64
 81 ad_landarea_medi_ct float64
 82 ad_livingapartments_medi_ct float64
 83 ad_livingarea_medi_ct float64
 84 ad_nonlivingapartments_medi_ct float64
 85 ad_nonlivingarea_medi_ct float64
 86 ad_fondkapremont_mode_ct object 
 87 ad_housetype_mode_ct object 
 88 ad_totalarea_mode_ct float64
 89 ad_wallsmaterial_mode_ct object 
 90 ad_emergencystate_mode_ct object 
 91 ad_obs_30_cnt_social_circle_ct float64
 92 ad_def_30_cnt_social_circle_ct float64
 93 ad_obs_60_cnt_social_circle_ct float64
 94 ad_def_60_cnt_social_circle_ct float64
 95 ad_days_last_phone_change_ct float64
 96 ad_flag_document_2_ct int64 
 97 ad_flag_document_3_ct int64 
 98 ad_flag_document_4_ct int64 
 99 ad_flag_document_5_ct int64 
 100 ad_flag_document_6_ct int64 
 101 ad_flag_document_7_ct int64 
 102 ad_flag_document_8_ct int64 
 103 ad_flag_document_9_ct int64 
 104 ad_flag_document_10_ct int64 
 105 ad_flag_document_11_ct int64 
 106 ad_flag_document_12_ct int64 
 107 ad_flag_document_13_ct int64 
 108 ad_flag_document_14_ct int64 
 10

In [0]:
#Task-6:Checking information of all columns of previous application dataset
ap_prev.info("all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 37 columns):
 # Column Non-Null Count Dtype 
--- ------ -------------- ----- 
 0 ad_sk_id_prev _ct 1048575 non-null int64 
 1 ad_sk_id_curr_ct 1048575 non-null int64 
 2 ad_name_contract_type_ct 1048575 non-null object 
 3 ad_amt_annuity_ct 815566 non-null float64
 4 ad_amt_application_ct 1048575 non-null float64
 5 ad_amt_credit_ct 1048575 non-null float64
 6 ad_amt_down_payment_ct 489179 non-null float64
 7 ad_amt_goods_price_ct 807610 non-null float64
 8 ad_weekday_appr_process_start_ct 1048575 non-null object 
 9 ad_hour_appr_process_start_ct 1048575 non-null int64 
 10 ad_flag_last_appl_per_contract_ct 1048575 non-null object 
 11 ad_nflag_last_appl_in_day_ct 1048575 non-null int64 
 12 ad_rate_down_payment_ct 489179 non-null float64
 13 ad_rate_interest_primary_ct 3721 non-null float64
 14 ad_rate_interest_privileged_ct 3721 non-null float64
 15 ad_name_cash_loan_purpose_ct 1048575 non-null object 
 16 ad_name_contract_status_ct 1048575 non-null object 
 17 ad_days_decision_ct 1048575 non-null int64 
 18 ad_name_payment_type_ct 1048575 non-null object 
 19 ad_code_reject_reason_ct 1048575 non-null object 
 20 ad_name_type_suite_ct 533435 non-null object 
 21 ad_name_client_type_ct 1048575 non-null object 
 22 ad_name_goods_category_ct 1048575 non-null object 
 23 ad_name_portfolio_ct 1048575 non-null object 
 24 ad_name_product_type_ct 1048575 non-null object 
 25 ad_channel_type_ct 1048575 non-null object 
 26 ad_sellerplace_area_ct 1048575 non-null int64 
 27 ad_name_seller_industry_ct 1048575 non-null object 
 28 ad_cnt_payment_ct 815569 non-null float64
 29 ad_name_yield_group_ct 1048575 non-null object 
 30 ad_product_combination_ct 1048351 non-null object 
 31 ad_days_first_drawing_ct 627867 non-null float64
 32 ad_days_first_due_ct 627867 non-null float64
 33 ad_days_last_due_1st_version_ct 627867 non-null float64
 34 ad_days_last_due_ct 627867 non-null float64
 35 ad_days_termination_ct 627867 non-null float64
 36 ad_nflag_insured_on_approval_ct 627867 non-null float64
dtypes: float64(15), int64(6), object(16)
memory usage: 296.0+ MB

In [0]:
#Task-7:Checking numeric values of dataframes
ap_data_num=ap_data.select_dtypes(include=['int64','float64'])
print('Shape of numeric variables of application dataset ',ap_data_num.shape)
ap_prev_num=ap_prev.select_dtypes(include=['int64','float64'])
print('Shape of numeric variables of previous application dataset ',ap_prev_num.shape)


Shape of numeric variables of application dataset (307511, 106)
Shape of numeric variables of previous application dataset (1048575, 21)

In [0]:
#Task-8:Data Cleaning & manipulation
#Count null values in application dataset
ap_data.isnull().sum()

Out[218]: ad_sk_id_curr_ct 0
ad_target_ct 0
ad_name_contract_type_ct 0
ad_code_gender_ct 0
ad_flag_own_car_ct 0
ad_flag_own_realty_ct 0
ad_cnt_children_ct 0
ad_amt_income_total_ct 0
ad_amt_credit_ct 0
ad_amt_annuity_ct 12
ad_amt_goods_price_ct 278
ad_name_type_suite_ct 1292
ad_name_income_type_ct 0
ad_name_education_type_ct 0
ad_name_family_status_ct 0
ad_name_housing_type_ct 0
ad_region_population_relative_ct 0
ad_days_birth_ct 0
ad_days_employed_ct 0
ad_days_registration_ct 0
ad_days_id_publish_ct 0
ad_own_car_age_ct 202929
ad_flag_mobil_ct 0
ad_flag_emp_phone_ct 0
ad_flag_work_phone_ct 0
ad_flag_cont_mobile_ct 0
ad_flag_phone_ct 0
ad_flag_email_ct 0
ad_occupation_type_ct 96391
ad_cnt_fam_members_ct 2
ad_region_rating_client_ct 0
ad_region_rating_client_w_city_ct 0
ad_weekday_appr_process_start_ct 0
ad_hour_appr_process_start_ct 0
ad_reg_region_not_live_region_ct 0
ad_reg_region_not_work_region_ct 0
ad_live_region_not_work_region_ct 0
ad_reg_city_not_live_city_ct 0
ad_reg_city_not_work_city_ct 0
ad_live_city_not_work_city_ct 0
ad_organization_type_ct 0
ad_ext_source_1_ct 173378
ad_ext_source_2_ct 660
ad_ext_source_3_ct 60965
ad_apartments_avg_ct 156061
ad_basementarea_avg_ct 179943
ad_years_beginexpluatation_avg_ct 150007
ad_years_build_avg_ct 204488
ad_commonarea_avg_ct 214865
ad_elevators_avg_ct 163891
ad_entrances_avg_ct 154828
ad_floorsmax_avg_ct 153020
ad_floorsmin_avg_ct 208642
ad_landarea_avg_ct 182590
ad_livingapartments_avg_ct 210199
ad_livingarea_avg_ct 154350
ad_nonlivingapartments_avg_ct 213514
ad_nonlivingarea_avg_ct 169682
ad_apartments_mode_ct 156061
ad_basementarea_mode_ct 179943
ad_years_beginexpluatation_mode_ct 150007
ad_years_build_mode_ct 204488
ad_commonarea_mode_ct 214865
ad_elevators_mode_ct 163891
ad_entrances_mode_ct 154828
ad_floorsmax_mode_ct 153020
ad_floorsmin_mode_ct 208642
ad_landarea_mode_ct 182590
ad_livingapartments_mode_ct 210199
ad_livingarea_mode_ct 154350
ad_nonlivingapartments_mode_ct 213514
ad_nonlivingarea_mode_ct 169682
ad_apartments_medi_ct 156061
ad_basementarea_medi_ct 179943
ad_years_beginexpluatation_medi_ct 150007
ad_years_build_medi_ct 204488
ad_commonarea_medi_ct 214865
ad_elevators_medi_ct 163891
ad_entrances_medi_ct 154828
ad_floorsmax_medi_ct 153020
ad_floorsmin_medi_ct 208642
ad_landarea_medi_ct 182590
ad_livingapartments_medi_ct 210199
ad_livingarea_medi_ct 154350
ad_nonlivingapartments_medi_ct 213514
ad_nonlivingarea_medi_ct 169682
ad_fondkapremont_mode_ct 210295
ad_housetype_mode_ct 154297
ad_totalarea_mode_ct 148431
ad_wallsmaterial_mode_ct 156341
ad_emergencystate_mode_ct 145755
ad_obs_30_cnt_social_circle_ct 1021
ad_def_30_cnt_social_circle_ct 1021
ad_obs_60_cnt_social_circle_ct 1021
ad_def_60_cnt_social_circle_ct 1021
ad_days_last_phone_change_ct 1
ad_flag_document_2_ct 0
ad_flag_document_3_ct 0
ad_flag_document_4_ct 0
ad_flag_document_5_ct 0
ad_flag_document_6_ct 0
ad_flag_document_7_ct 0
ad_flag_document_8_ct 0
ad_flag_document_9_ct 0
ad_flag_document_10_ct 0
ad_flag_document_11_ct 0
ad_flag_document_12_ct 0
ad_flag_document_13_ct 0
ad_flag_document_14_ct 0
ad_flag_document_15_ct 0
ad_flag_document_16_ct 0
ad_flag_document_17_ct 0
ad_flag_document_18_ct 0
ad_flag_document_19_ct 0
ad_flag_document_20_ct 0
ad_flag_document_21_ct 0
ad_amt_req_credit_bureau_hour_ct 41519
ad_amt_req_credit_bureau_day_ct 41519
ad_amt_req_credit_bureau_week_ct 41519
ad_amt_req_credit_bureau_mon_ct 41519
ad_amt_req_credit_bureau_qrt_ct 41519
ad_amt_req_credit_bureau_year_ct 41519
dtype: int64

In [0]:
#Count null values in previous application dataset
ap_prev.isnull().sum()

Out[219]: ad_sk_id_prev _ct 0
ad_sk_id_curr_ct 0
ad_name_contract_type_ct 0
ad_amt_annuity_ct 233009
ad_amt_application_ct 0
ad_amt_credit_ct 0
ad_amt_down_payment_ct 559396
ad_amt_goods_price_ct 240965
ad_weekday_appr_process_start_ct 0
ad_hour_appr_process_start_ct 0
ad_flag_last_appl_per_contract_ct 0
ad_nflag_last_appl_in_day_ct 0
ad_rate_down_payment_ct 559396
ad_rate_interest_primary_ct 1044854
ad_rate_interest_privileged_ct 1044854
ad_name_cash_loan_purpose_ct 0
ad_name_contract_status_ct 0
ad_days_decision_ct 0
ad_name_payment_type_ct 0
ad_code_reject_reason_ct 0
ad_name_type_suite_ct 515140
ad_name_client_type_ct 0
ad_name_goods_category_ct 0
ad_name_portfolio_ct 0
ad_name_product_type_ct 0
ad_channel_type_ct 0
ad_sellerplace_area_ct 0
ad_name_seller_industry_ct 0
ad_cnt_payment_ct 233006
ad_name_yield_group_ct 0
ad_product_combination_ct 224
ad_days_first_drawing_ct 420708
ad_days_first_due_ct 420708
ad_days_last_due_1st_version_ct 420708
ad_days_last_due_ct 420708
ad_days_termination_ct 420708
ad_nflag_insured_on_approval_ct 420708
dtype: int64

In [0]:
#Task-9:Count % of null values in application dataset
ap_data_null_per=100*ap_data.isnull().sum()/len(ap_data)
ap_data_null_per

Out[220]: ad_sk_id_curr_ct 0.000000
ad_target_ct 0.000000
ad_name_contract_type_ct 0.000000
ad_code_gender_ct 0.000000
ad_flag_own_car_ct 0.000000
ad_flag_own_realty_ct 0.000000
ad_cnt_children_ct 0.000000
ad_amt_income_total_ct 0.000000
ad_amt_credit_ct 0.000000
ad_amt_annuity_ct 0.003902
ad_amt_goods_price_ct 0.090403
ad_name_type_suite_ct 0.420148
ad_name_income_type_ct 0.000000
ad_name_education_type_ct 0.000000
ad_name_family_status_ct 0.000000
ad_name_housing_type_ct 0.000000
ad_region_population_relative_ct 0.000000
ad_days_birth_ct 0.000000
ad_days_employed_ct 0.000000
ad_days_registration_ct 0.000000
ad_days_id_publish_ct 0.000000
ad_own_car_age_ct 65.990810
ad_flag_mobil_ct 0.000000
ad_flag_emp_phone_ct 0.000000
ad_flag_work_phone_ct 0.000000
ad_flag_cont_mobile_ct 0.000000
ad_flag_phone_ct 0.000000
ad_flag_email_ct 0.000000
ad_occupation_type_ct 31.345545
ad_cnt_fam_members_ct 0.000650
ad_region_rating_client_ct 0.000000
ad_region_rating_client_w_city_ct 0.000000
ad_weekday_appr_process_start_ct 0.000000
ad_hour_appr_process_start_ct 0.000000
ad_reg_region_not_live_region_ct 0.000000
ad_reg_region_not_work_region_ct 0.000000
ad_live_region_not_work_region_ct 0.000000
ad_reg_city_not_live_city_ct 0.000000
ad_reg_city_not_work_city_ct 0.000000
ad_live_city_not_work_city_ct 0.000000
ad_organization_type_ct 0.000000
ad_ext_source_1_ct 56.381073
ad_ext_source_2_ct 0.214626
ad_ext_source_3_ct 19.825307
ad_apartments_avg_ct 50.749729
ad_basementarea_avg_ct 58.515956
ad_years_beginexpluatation_avg_ct 48.781019
ad_years_build_avg_ct 66.497784
ad_commonarea_avg_ct 69.872297
ad_elevators_avg_ct 53.295980
ad_entrances_avg_ct 50.348768
ad_floorsmax_avg_ct 49.760822
ad_floorsmin_avg_ct 67.848630
ad_landarea_avg_ct 59.376738
ad_livingapartments_avg_ct 68.354953
ad_livingarea_avg_ct 50.193326
ad_nonlivingapartments_avg_ct 69.432963
ad_nonlivingarea_avg_ct 55.179164
ad_apartments_mode_ct 50.749729
ad_basementarea_mode_ct 58.515956
ad_years_beginexpluatation_mode_ct 48.781019
ad_years_build_mode_ct 66.497784
ad_commonarea_mode_ct 69.872297
ad_elevators_mode_ct 53.295980
ad_entrances_mode_ct 50.348768
ad_floorsmax_mode_ct 49.760822
ad_floorsmin_mode_ct 67.848630
ad_landarea_mode_ct 59.376738
ad_livingapartments_mode_ct 68.354953
ad_livingarea_mode_ct 50.193326
ad_nonlivingapartments_mode_ct 69.432963
ad_nonlivingarea_mode_ct 55.179164
ad_apartments_medi_ct 50.749729
ad_basementarea_medi_ct 58.515956
ad_years_beginexpluatation_medi_ct 48.781019
ad_years_build_medi_ct 66.497784
ad_commonarea_medi_ct 69.872297
ad_elevators_medi_ct 53.295980
ad_entrances_medi_ct 50.348768
ad_floorsmax_medi_ct 49.760822
ad_floorsmin_medi_ct 67.848630
ad_landarea_medi_ct 59.376738
ad_livingapartments_medi_ct 68.354953
ad_livingarea_medi_ct 50.193326
ad_nonlivingapartments_medi_ct 69.432963
ad_nonlivingarea_medi_ct 55.179164
ad_fondkapremont_mode_ct 68.386172
ad_housetype_mode_ct 50.176091
ad_totalarea_mode_ct 48.268517
ad_wallsmaterial_mode_ct 50.840783
ad_emergencystate_mode_ct 47.398304
ad_obs_30_cnt_social_circle_ct 0.332021
ad_def_30_cnt_social_circle_ct 0.332021
ad_obs_60_cnt_social_circle_ct 0.332021
ad_def_60_cnt_social_circle_ct 0.332021
ad_days_last_phone_change_ct 0.000325
ad_flag_document_2_ct 0.000000
ad_flag_document_3_ct 0.000000
ad_flag_document_4_ct 0.000000
ad_flag_document_5_ct 0.000000
ad_flag_document_6_ct 0.000000
ad_flag_document_7_ct 0.000000
ad_flag_document_8_ct 0.000000
ad_flag_document_9_ct 0.000000
ad_flag_document_10_ct 0.000000
ad_flag_document_11_ct 0.000000
ad_flag_document_12_ct 0.000000
ad_flag_document_13_ct 0.000000
ad_flag_document_14_ct 0.000000
ad_flag_document_15_ct 0.000000
ad_flag_document_16_ct 0.000000
ad_flag_document_17_ct 0.000000
ad_flag_document_18_ct 0.000000
ad_flag_document_19_ct 0.000000
ad_flag_document_20_ct 0.000000
ad_flag_document_21_ct 0.000000
ad_amt_req_credit_bureau_hour_ct 13.501631
ad_amt_req_credit_bureau_day_ct 13.501631
ad_amt_req_credit_bureau_week_ct 13.501631
ad_amt_req_credit_bureau_mon_

In [0]:
#Task-9:Count % of null values in previous application dataset
ap_prev_null_per=100*ap_prev.isnull().sum()/len(ap_prev)
ap_prev_null_per

Out[221]: ad_sk_id_prev _ct 0.000000
ad_sk_id_curr_ct 0.000000
ad_name_contract_type_ct 0.000000
ad_amt_annuity_ct 22.221491
ad_amt_application_ct 0.000000
ad_amt_credit_ct 0.000000
ad_amt_down_payment_ct 53.348211
ad_amt_goods_price_ct 22.980235
ad_weekday_appr_process_start_ct 0.000000
ad_hour_appr_process_start_ct 0.000000
ad_flag_last_appl_per_contract_ct 0.000000
ad_nflag_last_appl_in_day_ct 0.000000
ad_rate_down_payment_ct 53.348211
ad_rate_interest_primary_ct 99.645137
ad_rate_interest_privileged_ct 99.645137
ad_name_cash_loan_purpose_ct 0.000000
ad_name_contract_status_ct 0.000000
ad_days_decision_ct 0.000000
ad_name_payment_type_ct 0.000000
ad_code_reject_reason_ct 0.000000
ad_name_type_suite_ct 49.127626
ad_name_client_type_ct 0.000000
ad_name_goods_category_ct 0.000000
ad_name_portfolio_ct 0.000000
ad_name_product_type_ct 0.000000
ad_channel_type_ct 0.000000
ad_sellerplace_area_ct 0.000000
ad_name_seller_industry_ct 0.000000
ad_cnt_payment_ct 22.221205
ad_name_yield_group_ct 0.000000
ad_product_combination_ct 0.021362
ad_days_first_drawing_ct 40.121880
ad_days_first_due_ct 40.121880
ad_days_last_due_1st_version_ct 40.121880
ad_days_last_due_ct 40.121880
ad_days_termination_ct 40.121880
ad_nflag_insured_on_approval_ct 40.121880
dtype: float64

In [0]:
#Task-10:Sort null values in application dataset
ap_data.isnull().sum().sort_values(ascending=False)

Out[222]: ad_commonarea_medi_ct 214865
ad_commonarea_avg_ct 214865
ad_commonarea_mode_ct 214865
ad_nonlivingapartments_mode_ct 213514
ad_nonlivingapartments_avg_ct 213514
ad_nonlivingapartments_medi_ct 213514
ad_fondkapremont_mode_ct 210295
ad_livingapartments_mode_ct 210199
ad_livingapartments_avg_ct 210199
ad_livingapartments_medi_ct 210199
ad_floorsmin_avg_ct 208642
ad_floorsmin_mode_ct 208642
ad_floorsmin_medi_ct 208642
ad_years_build_medi_ct 204488
ad_years_build_mode_ct 204488
ad_years_build_avg_ct 204488
ad_own_car_age_ct 202929
ad_landarea_medi_ct 182590
ad_landarea_mode_ct 182590
ad_landarea_avg_ct 182590
ad_basementarea_medi_ct 179943
ad_basementarea_avg_ct 179943
ad_basementarea_mode_ct 179943
ad_ext_source_1_ct 173378
ad_nonlivingarea_mode_ct 169682
ad_nonlivingarea_avg_ct 169682
ad_nonlivingarea_medi_ct 169682
ad_elevators_medi_ct 163891
ad_elevators_avg_ct 163891
ad_elevators_mode_ct 163891
ad_wallsmaterial_mode_ct 156341
ad_apartments_medi_ct 156061
ad_apartments_avg_ct 156061
ad_apartments_mode_ct 156061
ad_entrances_medi_ct 154828
ad_entrances_avg_ct 154828
ad_entrances_mode_ct 154828
ad_livingarea_avg_ct 154350
ad_livingarea_mode_ct 154350
ad_livingarea_medi_ct 154350
ad_housetype_mode_ct 154297
ad_floorsmax_mode_ct 153020
ad_floorsmax_medi_ct 153020
ad_floorsmax_avg_ct 153020
ad_years_beginexpluatation_mode_ct 150007
ad_years_beginexpluatation_medi_ct 150007
ad_years_beginexpluatation_avg_ct 150007
ad_totalarea_mode_ct 148431
ad_emergencystate_mode_ct 145755
ad_occupation_type_ct 96391
ad_ext_source_3_ct 60965
ad_amt_req_credit_bureau_hour_ct 41519
ad_amt_req_credit_bureau_day_ct 41519
ad_amt_req_credit_bureau_week_ct 41519
ad_amt_req_credit_bureau_mon_ct 41519
ad_amt_req_credit_bureau_qrt_ct 41519
ad_amt_req_credit_bureau_year_ct 41519
ad_name_type_suite_ct 1292
ad_obs_30_cnt_social_circle_ct 1021
ad_def_30_cnt_social_circle_ct 1021
ad_obs_60_cnt_social_circle_ct 1021
ad_def_60_cnt_social_circle_ct 1021
ad_ext_source_2_ct 660
ad_amt_goods_price_ct 278
ad_amt_annuity_ct 12
ad_cnt_fam_members_ct 2
ad_days_last_phone_change_ct 1
ad_cnt_children_ct 0
ad_flag_document_8_ct 0
ad_name_contract_type_ct 0
ad_code_gender_ct 0
ad_flag_own_car_ct 0
ad_flag_document_2_ct 0
ad_flag_document_3_ct 0
ad_flag_document_4_ct 0
ad_flag_document_5_ct 0
ad_flag_document_6_ct 0
ad_flag_document_7_ct 0
ad_flag_document_9_ct 0
ad_flag_document_21_ct 0
ad_flag_document_10_ct 0
ad_flag_document_11_ct 0
ad_flag_own_realty_ct 0
ad_flag_document_13_ct 0
ad_flag_document_14_ct 0
ad_flag_document_15_ct 0
ad_flag_document_16_ct 0
ad_flag_document_17_ct 0
ad_flag_document_18_ct 0
ad_flag_document_19_ct 0
ad_flag_document_20_ct 0
ad_flag_document_12_ct 0
ad_amt_credit_ct 0
ad_amt_income_total_ct 0
ad_flag_phone_ct 0
ad_live_city_not_work_city_ct 0
ad_reg_city_not_work_city_ct 0
ad_target_ct 0
ad_reg_city_not_live_city_ct 0
ad_live_region_not_work_region_ct 0
ad_reg_region_not_work_region_ct 0
ad_reg_region_not_live_region_ct 0
ad_hour_appr_process_start_ct 0
ad_weekday_appr_process_start_ct 0
ad_region_rating_client_w_city_ct 0
ad_region_rating_client_ct 0
ad_flag_email_ct 0
ad_flag_cont_mobile_ct 0
ad_organization_type_ct 0
ad_flag_work_phone_ct 0
ad_flag_emp_phone_ct 0
ad_flag_mobil_ct 0
ad_days_id_publish_ct 0
ad_days_registration_ct 0
ad_days_employed_ct 0
ad_days_birth_ct 0
ad_region_population_relative_ct 0
ad_name_housing_type_ct 0
ad_name_family_status_ct 0
ad_name_education_type_ct 0
ad_name_income_type_ct 0
ad_sk_id_curr_ct 0
dtype: int64

In [0]:
#Task-11:Sort null values in previous application dataset
ap_prev.isnull().sum().sort_values(ascending=False)

Out[223]: ad_rate_interest_privileged_ct 1044854
ad_rate_interest_primary_ct 1044854
ad_rate_down_payment_ct 559396
ad_amt_down_payment_ct 559396
ad_name_type_suite_ct 515140
ad_nflag_insured_on_approval_ct 420708
ad_days_first_drawing_ct 420708
ad_days_first_due_ct 420708
ad_days_last_due_1st_version_ct 420708
ad_days_last_due_ct 420708
ad_days_termination_ct 420708
ad_amt_goods_price_ct 240965
ad_amt_annuity_ct 233009
ad_cnt_payment_ct 233006
ad_product_combination_ct 224
ad_channel_type_ct 0
ad_name_product_type_ct 0
ad_name_yield_group_ct 0
ad_sellerplace_area_ct 0
ad_name_seller_industry_ct 0
ad_name_goods_category_ct 0
ad_name_portfolio_ct 0
ad_sk_id_prev _ct 0
ad_name_client_type_ct 0
ad_code_reject_reason_ct 0
ad_sk_id_curr_ct 0
ad_days_decision_ct 0
ad_name_contract_status_ct 0
ad_name_cash_loan_purpose_ct 0
ad_nflag_last_appl_in_day_ct 0
ad_flag_last_appl_per_contract_ct 0
ad_hour_appr_process_start_ct 0
ad_weekday_appr_process_start_ct 0
ad_amt_credit_ct 0
ad_amt_application_ct 0
ad_name_contract_type_ct 0
ad_name_payment_type_ct 0
dtype: int64

In [0]:
#Task-11:Dealing with null values more than 50% in application dataset
#Creating a variable null_col_50 for storing null columns having missing values more than 50%
null_col_50=ap_data_null_per[ap_data_null_per>50].index
null_col_50

Out[224]: Index(['ad_own_car_age_ct', 'ad_ext_source_1_ct', 'ad_apartments_avg_ct', 'ad_basementarea_avg_ct', 'ad_years_build_avg_ct', 'ad_commonarea_avg_ct', 'ad_elevators_avg_ct', 'ad_entrances_avg_ct', 'ad_floorsmin_avg_ct', 'ad_landarea_avg_ct', 'ad_livingapartments_avg_ct', 'ad_livingarea_avg_ct', 'ad_nonlivingapartments_avg_ct', 'ad_nonlivingarea_avg_ct', 'ad_apartments_mode_ct', 'ad_basementarea_mode_ct', 'ad_years_build_mode_ct', 'ad_commonarea_mode_ct', 'ad_elevators_mode_ct', 'ad_entrances_mode_ct', 'ad_floorsmin_mode_ct', 'ad_landarea_mode_ct', 'ad_livingapartments_mode_ct', 'ad_livingarea_mode_ct', 'ad_nonlivingapartments_mode_ct', 'ad_nonlivingarea_mode_ct', 'ad_apartments_medi_ct', 'ad_basementarea_medi_ct', 'ad_years_build_medi_ct', 'ad_commonarea_medi_ct', 'ad_elevators_medi_ct', 'ad_entrances_medi_ct', 'ad_floorsmin_medi_ct', 'ad_landarea_medi_ct', 'ad_livingapartments_medi_ct', 'ad_livingarea_medi_ct', 'ad_nonlivingapartments_medi_ct', 'ad_nonlivingarea_medi_ct',
 'ad_fondkapremont_mode_ct', 'ad_housetype_mode_ct', 'ad_wallsmaterial_mode_ct'],
 dtype='object')

In [0]:
#Task-11:Dealing with null values more than 50% in previous application dataset
#Creating a variable null_col_50_prev for storing null columns having missing values more than 50%
null_col_50_prev=ap_prev_null_per[ap_prev_null_per>50].index
null_col_50_prev

Out[225]: Index(['ad_amt_down_payment_ct', 'ad_rate_down_payment_ct', 'ad_rate_interest_primary_ct', 'ad_rate_interest_privileged_ct'], dtype='object')

In [0]:
#Task-12:Print number of columns having null values more than 50%
print('Number of columns having null values more than 50% in application is ',null_col_50.shape[0])
print('Number of columns having null values more than 50% in previous application is ',null_col_50_prev.shape[0])

Number of columns having null values more than 50% in application is 41
Number of columns having null values more than 50% in previous application is 4

In [0]:
#Task-13:Droping columns from application data which have null values greater than 50
ap_data_null_less_50=ap_data
ap_data_null_less_50=ap_data_null_less_50.drop(columns=null_col_50)
# ap_data_null_less_50.head()


In [0]:
#Task-13:Droping columns from previous application data which have null values greater than 50
ap_prev_null_less_50=ap_prev
ap_prev_null_less_50=ap_prev_null_less_50.drop(columns=null_col_50_prev)
# ap_prev_null_less_50.shape


In [0]:
#Task-14:Display and compare shape of application dataset after dropping all the columns having missing values more than 50%
print('Shape of application dataset after dropping all columns having null values more than 50% ',ap_data_null_less_50.shape)
print('Shape of original application dataset ',ap_data.shape)

Shape of application dataset after dropping all columns having null values more than 50% (307511, 81)
Shape of original application dataset (307511, 122)

In [0]:
#Task-14:Display and compare shape of previous application dataset after dropping all the columns having missing values more than 50%
print('Shape of previous application dataset after dropping all columns having null values more than 50% ',ap_prev_null_less_50.shape)
print('Shape of original previous application dataset ',ap_prev.shape)

Shape of previous application dataset after dropping all columns having null values more than 50% (1048575, 33)
Shape of original previous application dataset (1048575, 37)

In [0]:
#Task-15:Dealing with null values more than 0% in application dataset
ap_data_null_per_0=100*ap_data_null_less_50.isnull().sum()/len(ap_data)
# ap_data_null_per_0
null_col_0=ap_data_null_per_0[ap_data_null_per_0>0].index
null_col_0

Out[231]: Index(['ad_amt_annuity_ct', 'ad_amt_goods_price_ct', 'ad_name_type_suite_ct', 'ad_occupation_type_ct', 'ad_cnt_fam_members_ct', 'ad_ext_source_2_ct', 'ad_ext_source_3_ct', 'ad_years_beginexpluatation_avg_ct', 'ad_floorsmax_avg_ct', 'ad_years_beginexpluatation_mode_ct', 'ad_floorsmax_mode_ct', 'ad_years_beginexpluatation_medi_ct', 'ad_floorsmax_medi_ct', 'ad_totalarea_mode_ct', 'ad_emergencystate_mode_ct', 'ad_obs_30_cnt_social_circle_ct', 'ad_def_30_cnt_social_circle_ct', 'ad_obs_60_cnt_social_circle_ct', 'ad_def_60_cnt_social_circle_ct', 'ad_days_last_phone_change_ct', 'ad_amt_req_credit_bureau_hour_ct', 'ad_amt_req_credit_bureau_day_ct', 'ad_amt_req_credit_bureau_week_ct', 'ad_amt_req_credit_bureau_mon_ct', 'ad_amt_req_credit_bureau_qrt_ct', 'ad_amt_req_credit_bureau_year_ct'], dtype='object')

In [0]:
#Task-15:Dealing with null values more than 0% in previous application dataset
ap_prev_null_per_0=100*ap_prev_null_less_50.isnull().sum()/len(ap_prev)
# ap_data_null_per_0
null_col_0_prev=ap_prev_null_per_0[ap_prev_null_per_0>0].index
null_col_0_prev

Out[232]: Index(['ad_amt_annuity_ct', 'ad_amt_goods_price_ct', 'ad_name_type_suite_ct', 'ad_cnt_payment_ct', 'ad_product_combination_ct', 'ad_days_first_drawing_ct', 'ad_days_first_due_ct', 'ad_days_last_due_1st_version_ct', 'ad_days_last_due_ct', 'ad_days_termination_ct', 'ad_nflag_insured_on_approval_ct'], dtype='object')

In [0]:
#Task-16:Removing null values from application dataset having null values more than 0%
ap_data_null_more_0=ap_data_null_less_50
ap_data_null_more_0=ap_data_null_more_0.drop(columns=null_col_0)
# ap_data_null_more_0.shape



In [0]:
#Task-16:Droping columns from previous application data which have null values greater than 50
ap_prev_null_more_0=ap_prev_null_less_50
ap_prev_null_more_0=ap_prev_null_more_0.drop(columns=null_col_0_prev)
# ap_prev_null_less_50.shape


In [0]:
#Task-17:Display and compare shape of application dataset after drop all the columns having missing values more than 0%
print('Shape of application dataset after dropping all columns having null values more than 0% ',ap_data_null_more_0.shape)
print('Shape of application dataset after dropping all columns having null values more than 50% ',ap_data_null_less_50.shape)

Shape of application dataset after dropping all columns having null values more than 0% (307511, 55)
Shape of application dataset after dropping all columns having null values more than 50% (307511, 81)

In [0]:
#Task-17:Display and compare shape of previous application dataset after drop all the columns having missing values more than 0%
print('Shape of previous application dataset after dropping all columns having null values more than 0% ',ap_prev_null_more_0.shape)
print('Shape of previous application dataset after dropping all columns having null values more than 50% ',ap_prev_null_less_50.shape)

Shape of previous application dataset after dropping all columns having null values more than 0% (1048575, 22)
Shape of previous application dataset after dropping all columns having null values more than 50% (1048575, 33)

In [0]:
#To confirm that there is no null values which have more than 0% in application dataset
print('Shape of application dataset after dropping all columns having null values more than 0% ',ap_data_null_more_0.shape)
print('Shape of original application dataset ',ap_data.shape)

Shape of application dataset after dropping all columns having null values more than 0% (307511, 55)
Shape of original application dataset (307511, 122)

In [0]:
#To confirm that there is no null values which have more than 0% in previous application dataset
print('Shape of previous application dataset after dropping all columns having null values more than 0% ',ap_prev_null_more_0.shape)
print('Shape of original previous application dataset ',ap_prev.shape)

Shape of previous application dataset after dropping all columns having null values more than 0% (1048575, 22)
Shape of original previous application dataset (1048575, 37)

In [0]:
#Task-18:Collect columns in application datset having 0 null values
ap_data_null_more_0.head ()

Out[239]:

ad_sk_id_curr_ct 
 ad_target_ct 
 ad_name_contract_type_ct 
 ad_code_gender_ct 
 ad_flag_own_car_ct 
 ad_flag_own_realty_ct 
 ad_cnt_children_ct 
 ad_amt_income_total_ct 
 ad_amt_credit_ct 
 ad_name_income_type_ct 
 ad_name_education_type_ct 
 ad_name_family_status_ct 
 ad_name_housing_type_ct 
 ad_region_population_relative_ct 
 ad_days_birth_ct 
 ad_days_employed_ct 
 ad_days_registration_ct 
 ad_days_id_publish_ct 
 ad_flag_mobil_ct 
 ad_flag_emp_phone_ct 
 ad_flag_work_phone_ct 
 ad_flag_cont_mobile_ct 
 ad_flag_phone_ct 
 ad_flag_email_ct 
 ad_region_rating_client_ct 
 ad_region_rating_client_w_city_ct 
 ad_weekday_appr_process_start_ct 
 ad_hour_appr_process_start_ct 
 ad_reg_region_not_live_region_ct 
 ad_reg_region_not_work_region_ct 
 ad_live_region_not_work_region_ct 
 ad_reg_city_not_live_city_ct 
 ad_reg_city_not_work_city_ct 
 ad_live_city_not_work_city_ct 
 ad_organization_type_ct 
 ad_flag_document_2_ct 
 ad_flag_document_3_ct 
 ad_flag_document_4_ct 
 ad_flag_document_5_ct 
 ad_flag_document_6_ct 
 ad_flag_document_7_ct 
 ad_flag_document_8_ct 
 ad_flag_document_9_ct 
 ad_flag_document_10_ct 
 ad_flag_document_11_ct 
 ad_flag_document_12_ct 
 ad_flag_document_13_ct 
 ad_flag_document_14_ct 
 ad_flag_document_15_ct 
 ad_flag_document_16_ct 
 ad_flag_document_17_ct 
 ad_flag_document_18_ct 
 ad_flag_document_19_ct 
 ad_flag_document_20_ct 
 ad_flag_document_21_ct 
 
 
 
 
 0 
 100002 
 1 
 Cash loans 
 M 
 N 
 Y 
 0 
 202500.0 
 406597.5 
 Working 
 Secondary / secondary special 
 Single / not married 
 House / apartment 
 0.018801 
 -9461 
 -637 
 -3648.0 
 -2120 
 1 
 1 
 0 
 1 
 1 
 0 
 2 
 2 
 WEDNESDAY 
 10 
 0 
 0 
 0 
 0 
 0 
 0 
 Business Entity Type 3 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 1 
 100003 
 0 
 Cash loans 
 F 
 N 
 N 
 0 
 270000.0 
 1293502.5 
 State servant 
 Higher education 
 Married 
 House / apartment 
 0.003541 
 -16765 
 -1188 
 -1186.0 
 -291 
 1 
 1 
 0 
 1 
 1 
 0 
 1 
 1 
 MONDAY 
 11 
 0 
 0 
 0 
 0 
 0 
 0 
 School 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 2 
 100004 
 0 
 Revolving loans 
 M 
 Y 
 Y 
 0 
 67500.0 
 135000.0 
 Working 
 Secondary / secondary special 
 Single / not married 
 House / apartment 
 0.010032 
 -19046 
 -225 
 -4260.0 
 -2531 
 1 
 1 
 1 
 1 
 1 
 0 
 2 
 2 
 MONDAY 
 9 
 0 
 0 
 0 
 0 
 0 
 0 
 Government 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 3 
 100006 
 0 
 Cash loans 
 F 
 N 
 Y 
 0 
 135000.0 
 312682.5 
 Working 
 Secondary / secondary special 
 Civil marriage 
 House / apartment 
 0.008019 
 -19005 
 -3039 
 -9833.0 
 -2437 
 1 
 1 
 0 
 1 
 0 
 0 
 2 
 2 
 WEDNESDAY 
 17 
 0 
 0 
 0 
 0 
 0 
 0 
 Business Entity Type 3 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 4 
 100007 
 0 
 Cash loans 
 M 
 N 
 Y 
 0 
 121500.0 
 513000.0 
 Working 
 Secondary / secondary special 
 Single / not married 
 House / apartment 
 0.028663 
 -19932 
 -3038 
 -4311.0 
 -3458 
 1 
 1 
 0 
 1 
 0 
 0 
 2 
 2 
 THURSDAY 
 11 
 0 
 0 
 0 
 0 
 1 
 1 
 Religion 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0

In [0]:
#Task-18:Collect columns in previous application dataset having 0 null values
ap_prev_null_more_0.head()

Out[240]:

ad_sk_id_prev _ct 
 ad_sk_id_curr_ct 
 ad_name_contract_type_ct 
 ad_amt_application_ct 
 ad_amt_credit_ct 
 ad_weekday_appr_process_start_ct 
 ad_hour_appr_process_start_ct 
 ad_flag_last_appl_per_contract_ct 
 ad_nflag_last_appl_in_day_ct 
 ad_name_cash_loan_purpose_ct 
 ad_name_contract_status_ct 
 ad_days_decision_ct 
 ad_name_payment_type_ct 
 ad_code_reject_reason_ct 
 ad_name_client_type_ct 
 ad_name_goods_category_ct 
 ad_name_portfolio_ct 
 ad_name_product_type_ct 
 ad_channel_type_ct 
 ad_sellerplace_area_ct 
 ad_name_seller_industry_ct 
 ad_name_yield_group_ct 
 
 
 
 
 0 
 2030495 
 271877 
 Consumer loans 
 17145.0 
 17145.0 
 SATURDAY 
 15 
 Y 
 1 
 XAP 
 Approved 
 -73 
 Cash through the bank 
 XAP 
 Repeater 
 Mobile 
 POS 
 XNA 
 Country-wide 
 35 
 Connectivity 
 middle 
 
 
 1 
 2802425 
 108129 
 Cash loans 
 607500.0 
 679671.0 
 THURSDAY 
 11 
 Y 
 1 
 XNA 
 Approved 
 -164 
 XNA 
 XAP 
 Repeater 
 XNA 
 Cash 
 x-sell 
 Contact center 
 -1 
 XNA 
 low_action 
 
 
 2 
 2523466 
 122040 
 Cash loans 
 112500.0 
 136444.5 
 TUESDAY 
 11 
 Y 
 1 
 XNA 
 Approved 
 -301 
 Cash through the bank 
 XAP 
 Repeater 
 XNA 
 Cash 
 x-sell 
 Credit and cash offices 
 -1 
 XNA 
 high 
 
 
 3 
 2819243 
 176158 
 Cash loans 
 450000.0 
 470790.0 
 MONDAY 
 7 
 Y 
 1 
 XNA 
 Approved 
 -512 
 Cash through the bank 
 XAP 
 Repeater 
 XNA 
 Cash 
 x-sell 
 Credit and cash offices 
 -1 
 XNA 
 middle 
 
 
 4 
 1784265 
 202054 
 Cash loans 
 337500.0 
 404055.0 
 THURSDAY 
 9 
 Y 
 1 
 Repairs 
 Refused 
 -781 
 Cash through the bank 
 HC 
 Repeater 
 XNA 
 Cash 
 walk-in 
 Credit and cash offices 
 -1 
 XNA 
 high

In [0]:
#Task-19:Display unique values in application dataset
col=ap_data_null_more_0.columns.values
# type(coln)

# print(ap_data_null_more_0[coln[6]].unique()
for i in range(ap_data_null_more_0.shape[1]):
    print(ap_data_null_more_0[col[i]].unique())

[100002 100003 100004 ... 456253 456254 456255]
[1 0]
['Cash loans' 'Revolving loans']
['M' 'F' 'XNA']
['N' 'Y']
['Y' 'N']
[ 0 1 2 3 4 7 5 6 8 9 11 12 10 19 14]
[202500. 270000. 67500. ... 96768. 546250.5 113062.5]
[ 406597.5 1293502.5 135000. ... 181989. 743863.5 1391130. ]
['Working' 'State servant' 'Commercial associate' 'Pensioner' 'Unemployed'
 'Student' 'Businessman' 'Maternity leave']
['Secondary / secondary special' 'Higher education' 'Incomplete higher'
 'Lower secondary' 'Academic degree']
['Single / not married' 'Married' 'Civil marriage' 'Widow' 'Separated'
 'Unknown']
['House / apartment' 'Rented apartment' 'With parents'
 'Municipal apartment' 'Office apartment' 'Co-op apartment']
[0.018801 0.003541 0.010032 0.008019 0.028663 0.035792 0.003122 0.018634
 0.019689 0.0228 0.015221 0.031329 0.016612 0.010006 0.020713 0.010966
 0.04622 0.025164 0.006296 0.026392 0.018029 0.019101 0.030755 0.008575
 0.01885 0.006207 0.009175 0.007305 0.007114 0.009334 0.022625 0.01452
 0.006629 0.00733 0.032561 0.00496 0.072508 0.009657 0.02461 0.003069
 0.020246 0.018209 0.009549 0.007274 0.002134 0.010276 0.003813 0.003818
 0.00712 0.0105 0.010147 0.010643 0.008866 0.00702 0.002506 0.005313
 0.006233 0.008474 0.005144 0.011657 0.008625 0.014464 0.004849 0.006008
 0.00963 0.005002 0.006852 0.011703 0.006305 0.010556 0.00823 0.006671
 0.002042 0.005084 0.008068 0.001333 0.001417 0.001276 0.000938 0.000533
 0.00029 ]
[ -9461 -16765 -19046 ... -7951 -7857 -25061]
[ -637 -1188 -225 ... -12971 -11084 -8694]
[ -3648. -1186. -4260. ... -16396. -14558. -14798.]
[-2120 -291 -2531 ... -6194 -5854 -6211]
[1 0]
[1 0]
[0 1]
[1 0]
[1 0]
[0 1]
[2 1 3]
[2 1 3]
['WEDNESDAY' 'MONDAY' 'THURSDAY' 'SUNDAY' 'SATURDAY' 'FRIDAY' 'TUESDAY']
[10 11 9 17 16 14 8 15 7 13 6 12 19 3 18 21 4 5 20 22 1 2 23 0]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
['Business Entity Type 3' 'School' 'Government' 'Religion' 'Other' 'XNA'
 'Electricity' 'Medicine' 'Business Entity Type 2' 'Self-employed'
 'Transport: type 2' 'Construction' 'Housing' 'Kindergarten'
 'Trade: type 7' 'Industry: type 11' 'Military' 'Services'
 'Security Ministries' 'Transport: type 4' 'Industry: type 1' 'Emergency'
 'Security' 'Trade: type 2' 'University' 'Transport: type 3' 'Police'
 'Business Entity Type 1' 'Postal' 'Industry: type 4' 'Agriculture'
 'Restaurant' 'Culture' 'Hotel' 'Industry: type 7' 'Trade: type 3'
 'Industry: type 3' 'Bank' 'Industry: type 9' 'Insurance' 'Trade: type 6'
 'Industry: type 2' 'Transport: type 1' 'Industry: type 12' 'Mobile'
 'Trade: type 1' 'Industry: type 5' 'Industry: type 10' 'Legal Services'
 'Advertising' 'Trade: type 5' 'Cleaning' 'Industry: type 13'
 'Trade: type 4' 'Telecom' 'Industry: type 8' 'Realtor' 'Industry: type 6']
[0 1]
[1 0]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[0 1]

In [0]:
#Task-19:Display unique values in previous application dataset
coln=ap_prev_null_more_0.columns.values
for i in range(ap_prev_null_more_0.shape[1]):
    print(ap_prev_null_more_0[coln[i]].unique())

[2030495 2802425 2523466 ... 1730537 2100360 1283481]
[271877 108129 122040 ... 182836 195080 287184]
['Consumer loans' 'Cash loans' 'Revolving loans' 'XNA']
[ 17145. 607500. 112500. ... 1465200. 61243.65 319306.5 ]
[ 17145. 679671. 136444.5 ... 1271700. 184918.5 189864. ]
['SATURDAY' 'THURSDAY' 'TUESDAY' 'MONDAY' 'FRIDAY' 'SUNDAY' 'WEDNESDAY']
[15 11 7 9 8 10 12 13 14 16 6 4 5 19 17 18 20 22 21 3 1 2 23 0]
['Y' 'N']
[1 0]
['XAP' 'XNA' 'Repairs' 'Everyday expenses' 'Car repairs'
 'Building a house or an annex' 'Other' 'Journey'
 'Purchase of electronic equipment' 'Medicine' 'Payments on other loans'
 'Urgent needs' 'Buying a used car' 'Buying a new car'
 'Buying a holiday home / land' 'Education' 'Buying a home' 'Furniture'
 'Buying a garage' 'Business development' 'Wedding / gift / holiday'
 'Hobby' 'Gasification / water supply' 'Refusal to name the goal'
 'Money for a third person']
['Approved' 'Refused' 'Canceled' 'Unused offer']
[ -73 -164 -301 ... -2262 -1967 -2389]
['Cash through the bank' 'XNA' 'Non-cash from your account'
 'Cashless from the account of the employer']
['XAP' 'HC' 'LIMIT' 'CLIENT' 'SCOFR' 'SCO' 'XNA' 'VERIF' 'SYSTEM']
['Repeater' 'New' 'Refreshed' 'XNA']
['Mobile' 'XNA' 'Consumer Electronics' 'Construction Materials'
 'Auto Accessories' 'Photo / Cinema Equipment' 'Computers' 'Audio/Video'
 'Medicine' 'Clothing and Accessories' 'Furniture' 'Sport and Leisure'
 'Homewares' 'Gardening' 'Jewelry' 'Vehicles' 'Education'
 'Medical Supplies' 'Other' 'Direct Sales' 'Office Appliances' 'Fitness'
 'Tourism' 'Insurance' 'Additional Service' 'Weapon' 'Animals'
 'House Construction']
['POS' 'Cash' 'XNA' 'Cards' 'Cars']
['XNA' 'x-sell' 'walk-in']
['Country-wide' 'Contact center' 'Credit and cash offices' 'Stone'
 'Regional / Local' 'AP+ (Cash loan)' 'Channel of corporate sales'
 'Car dealer']
[ 35 -1 200 ... 5557 3322 2867]
['Connectivity' 'XNA' 'Consumer electronics' 'Industry' 'Clothing'
 'Furniture' 'Construction' 'Jewelry' 'Auto technology' 'MLM partners'
 'Tourism']
['middle' 'low_action' 'high' 'low_normal' 'XNA']

In [0]:
#importing label encoder library
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [0]:
#Task-20:Viewing flag columns in application dataset
ap_data_clean_flag=ap_data_null_more_0.filter(like='flag')
ap_data_clean_flag.head()

Out[244]:

ad_flag_own_car_ct 
 ad_flag_own_realty_ct 
 ad_flag_mobil_ct 
 ad_flag_emp_phone_ct 
 ad_flag_work_phone_ct 
 ad_flag_cont_mobile_ct 
 ad_flag_phone_ct 
 ad_flag_email_ct 
 ad_flag_document_2_ct 
 ad_flag_document_3_ct 
 ad_flag_document_4_ct 
 ad_flag_document_5_ct 
 ad_flag_document_6_ct 
 ad_flag_document_7_ct 
 ad_flag_document_8_ct 
 ad_flag_document_9_ct 
 ad_flag_document_10_ct 
 ad_flag_document_11_ct 
 ad_flag_document_12_ct 
 ad_flag_document_13_ct 
 ad_flag_document_14_ct 
 ad_flag_document_15_ct 
 ad_flag_document_16_ct 
 ad_flag_document_17_ct 
 ad_flag_document_18_ct 
 ad_flag_document_19_ct 
 ad_flag_document_20_ct 
 ad_flag_document_21_ct 
 
 
 
 
 0 
 N 
 Y 
 1 
 1 
 0 
 1 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 1 
 N 
 N 
 1 
 1 
 0 
 1 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 2 
 Y 
 Y 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 3 
 N 
 Y 
 1 
 1 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 4 
 N 
 Y 
 1 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0

In [0]:
#Label encoding application dataset
ap_data_clean_flag.ad_flag_own_car_ct = le.fit_transform(ap_data_clean_flag.ad_flag_own_car_ct)
ap_data_clean_flag.ad_flag_own_realty_ct = le.fit_transform(ap_data_clean_flag.ad_flag_own_realty_ct)

In [0]:
#After label encoding
ap_data_clean_flag.head()

Out[246]:

ad_flag_own_car_ct 
 ad_flag_own_realty_ct 
 ad_flag_mobil_ct 
 ad_flag_emp_phone_ct 
 ad_flag_work_phone_ct 
 ad_flag_cont_mobile_ct 
 ad_flag_phone_ct 
 ad_flag_email_ct 
 ad_flag_document_2_ct 
 ad_flag_document_3_ct 
 ad_flag_document_4_ct 
 ad_flag_document_5_ct 
 ad_flag_document_6_ct 
 ad_flag_document_7_ct 
 ad_flag_document_8_ct 
 ad_flag_document_9_ct 
 ad_flag_document_10_ct 
 ad_flag_document_11_ct 
 ad_flag_document_12_ct 
 ad_flag_document_13_ct 
 ad_flag_document_14_ct 
 ad_flag_document_15_ct 
 ad_flag_document_16_ct 
 ad_flag_document_17_ct 
 ad_flag_document_18_ct 
 ad_flag_document_19_ct 
 ad_flag_document_20_ct 
 ad_flag_document_21_ct 
 
 
 
 
 0 
 0 
 1 
 1 
 1 
 0 
 1 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 1 
 0 
 0 
 1 
 1 
 0 
 1 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 2 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 3 
 0 
 1 
 1 
 1 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 
 
 4 
 0 
 1 
 1 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0 
 0

In [0]:
#Task-19:Viewing flag columns in previous application dataset
ap_prev_clean_flag=ap_prev_null_more_0.filter(like='flag')
ap_prev_clean_flag.head()

Out[247]:

ad_flag_last_appl_per_contract_ct 
 ad_nflag_last_appl_in_day_ct 
 
 
 
 
 0 
 Y 
 1 
 
 
 1 
 Y 
 1 
 
 
 2 
 Y 
 1 
 
 
 3 
 Y 
 1 
 
 
 4 
 Y 
 1

In [0]:
#Label encoding previous application dataset
ap_prev_clean_flag.ad_flag_last_appl_per_contract_ct = le.fit_transform(ap_prev_clean_flag.ad_flag_last_appl_per_contract_ct)

In [0]:
#After label encoding
ap_prev_clean_flag.ad_flag_last_appl_per_contract_ct.unique()

Out[249]: array([1, 0])

In [0]:
#Duplicating the cleaned datasets
ap_data_clean=ap_data_null_more_0
ap_prev_clean=ap_prev_null_more_0

##EDA

In [0]:
#importing libraries
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [0]:
#Correlation of application dataset
crd=ap_data_clean_flag.corr()
crd

Out[252]:

ad_flag_own_car_ct 
 ad_flag_own_realty_ct 
 ad_flag_mobil_ct 
 ad_flag_emp_phone_ct 
 ad_flag_work_phone_ct 
 ad_flag_cont_mobile_ct 
 ad_flag_phone_ct 
 ad_flag_email_ct 
 ad_flag_document_2_ct 
 ad_flag_document_3_ct 
 ad_flag_document_4_ct 
 ad_flag_document_5_ct 
 ad_flag_document_6_ct 
 ad_flag_document_7_ct 
 ad_flag_document_8_ct 
 ad_flag_document_9_ct 
 ad_flag_document_10_ct 
 ad_flag_document_11_ct 
 ad_flag_document_12_ct 
 ad_flag_document_13_ct 
 ad_flag_document_14_ct 
 ad_flag_document_15_ct 
 ad_flag_document_16_ct 
 ad_flag_document_17_ct 
 ad_flag_document_18_ct 
 ad_flag_document_19_ct 
 ad_flag_document_20_ct 
 ad_flag_document_21_ct 
 
 
 
 
 ad_flag_own_car_ct 
 1.000000 
 -0.002817 
 -0.002512 
 0.154659 
 0.011471 
 -0.006644 
 -0.007588 
 0.032105 
 -0.000445 
 -0.070000 
 -0.001144 
 -0.013661 
 -0.106012 
 0.000958 
 0.228368 
 -0.011069 
 0.000891 
 -0.000456 
 0.003552 
 0.080647 
 0.003410 
 0.045909 
 0.001984 
 -0.002476 
 -0.000097 
 0.002184 
 0.007299 
 0.006741 
 
 
 ad_flag_own_realty_ct 
 -0.002817 
 1.000000 
 -0.001198 
 -0.070021 
 -0.114043 
 0.008526 
 -0.041507 
 0.029247 
 0.003236 
 -0.036839 
 0.002080 
 -0.011922 
 0.041567 
 0.003093 
 -0.035077 
 -0.003513 
 0.003171 
 -0.035201 
 -0.001071 
 -0.057484 
 -0.054678 
 -0.035729 
 -0.092272 
 -0.014207 
 -0.087687 
 -0.019364 
 -0.025130 
 -0.000173 
 
 
 ad_flag_mobil_ct 
 -0.002512 
 -0.001198 
 1.000000 
 -0.000845 
 0.000900 
 -0.000078 
 0.001128 
 0.000442 
 0.000012 
 0.002822 
 0.000016 
 0.000223 
 0.000560 
 0.000025 
 -0.006059 
 0.000113 
 0.000009 
 0.000113 
 0.000005 
 0.000107 
 0.000098 
 0.000063 
 0.000181 
 0.000029 
 -0.019919 
 0.000044 
 0.000041 
 0.000033 
 
 
 ad_flag_emp_phone_ct 
 0.154659 
 -0.070021 
 -0.000845 
 1.000000 
 0.233801 
 -0.012819 
 -0.016131 
 0.062542 
 0.003047 
 0.248534 
 -0.000467 
 0.019778 
 -0.597732 
 0.001605 
 0.122043 
 0.023878 
 0.000463 
 0.029373 
 0.001195 
 0.025878 
 0.023559 
 0.014364 
 0.043008 
 0.007136 
 0.040548 
 0.010049 
 0.010183 
 0.008579 
 
 
 ad_flag_work_phone_ct 
 0.011471 
 -0.114043 
 0.000900 
 0.233801 
 1.000000 
 0.021580 
 0.293105 
 -0.011520 
 -0.001993 
 0.060342 
 -0.004500 
 0.036847 
 -0.138345 
 0.001902 
 0.021464 
 0.008252 
 0.002737 
 0.123500 
 -0.001273 
 0.001769 
 -0.002712 
 0.007689 
 0.005692 
 0.001322 
 0.032049 
 0.011854 
 0.001771 
 0.001541 
 
 
 ad_flag_cont_mobile_ct 
 -0.006644 
 0.008526 
 -0.000078 
 -0.012819 
 0.021580 
 1.000000 
 0.006257 
 -0.005356 
 0.000281 
 0.006235 
 0.000390 
 0.005357 
 0.009981 
 -0.004841 
 -0.022400 
 -0.008180 
 0.000206 
 0.002710 
 0.000110 
 -0.064800 
 -0.072839 
 -0.013667 
 -0.030625 
 -0.013136 
 -0.043068 
 -0.005123 
 0.000974 
 -0.015677 
 
 
 ad_flag_phone_ct 
 -0.007588 
 -0.041507 
 0.001128 
 -0.016131 
 0.293105 
 0.006257 
 1.000000 
 0.014657 
 -0.000728 
 -0.008020 
 0.003990 
 0.075455 
 0.009836 
 0.013276 
 0.004778 
 0.012923 
 0.004598 
 0.003231 
 -0.001595 
 0.006997 
 0.010321 
 0.008001 
 0.010354 
 0.004410 
 0.004055 
 0.009660 
 0.000692 
 0.000020 
 
 
 ad_flag_email_ct 
 0.032105 
 0.029247 
 0.000442 
 0.062542 
 -0.011520 
 -0.005356 
 0.014657 
 1.000000 
 0.002730 
 0.012015 
 0.002467 
 0.000734 
 -0.042660 
 0.001678 
 0.030474 
 0.009490 
 0.001777 
 -0.003656 
 -0.000625 
 -0.003436 
 0.001502 
 -0.003276 
 -0.012644 
 -0.001422 
 -0.008110 
 -0.002525 
 -0.001778 
 -0.000647 
 
 
 ad_flag_document_2_ct 
 -0.000445 
 0.003236 
 0.000012 
 0.003047 
 -0.001993 
 0.000281 
 -0.000728 
 0.002730 
 1.000000 
 -0.010174 
 -0.000059 
 -0.000805 
 -0.002020 
 -0.000090 
 -0.001935 
 -0.000407 
 -0.000031 
 -0.000407 
 -0.000017 
 -0.000387 
 -0.000353 
 -0.000226 
 -0.000651 
 -0.000106 
 -0.000589 
 -0.000159 
 -0.000146 
 -0.000119 
 
 
 ad_flag_document_3_ct 
 -0.070000 
 -0.036839 
 0.002822 
 0.248534 
 0.060342 
 0.006235 
 -0.008020 
 0.012015 
 -0.010174 
 1.000000 
 -0.014110 
 -0.193850 
 -0.486238 
 -0.021677 
 -0.465730 
 -0.097859 
 -0

In [0]:
#Correlation of previous application dataset
cr=ap_prev_clean_flag.corr()
cr

Out[253]:

ad_flag_last_appl_per_contract_ct 
 ad_nflag_last_appl_in_day_ct 
 
 
 
 
 ad_flag_last_appl_per_contract_ct 
 1.000000 
 0.723814 
 
 
 ad_nflag_last_appl_in_day_ct 
 0.723814 
 1.000000